boostorg/core

include/boost/core/ignore_unused.hpp
test/ignore_unused_test.cpp

Add C++14 constexpr by BOOST_CXX14_CONSTEXPR.
Replace inline with BOOST_FORCEINLINE.

[core] Add/improve ignore_unused() function specifiers.

---

doc/enable_if.qbk
include/boost/core/enable_if.hpp
test/eif_partial_specializations.cpp

Provides an autonomous of enable_if_has_type which enable SFIANE checks on type existence.
Renamed enable_if_has_type after discussions on the Bosot dev ML.

Enable_if_has_type

---

include/boost/core/addressof.hpp
test/Jamfile.v2
test/addressof_constexpr_test.cpp

Putting the pull request up for discussion: C++17 provides constexpr addressof, which we can provide in C++11 and above when specific language features are supported by the implementation (e.g. expression SFINAE and constexpr). Do we want this?
I will add the MSVC workarounds back and update the pull request. The Sun and Borland workarounds don't have to be removed either.

Implement constexpr addressof

---

include/boost/core/addressof.hpp

The test case could check for BOOST_NO_CXX11_CONSTEXPR but it makes sense for BOOST_CORE_NO_CONSTEXPR_ADDRESSOF to be defined in this case also.

Define CORE_NO_CONSTEXPR_ADDRESSOF if NO_CXX11_CONSTEXPR is defined

---

include/boost/core/addressof.hpp

Travis script indicates that it pulls from git directly so it should get the latest Config develop.

Use new BOOST_NO_CXX11_SFINAE_EXPR feature macro

---

include/boost/core/addressof.hpp
test/Jamfile.v2
test/addressof_constexpr_test.cpp
test/addressof_fail_rvalue.cpp

Now in C++17: `template<class T> const T* addressof(const T&&) = delete;`

Also disable addressof for r-values when possible

---

doc/lightweight_test.qbk
include/boost/core/lightweight_test.hpp
test/Jamfile.v2
test/lightweight_test_ge_fail.cpp
test/lightweight_test_gt_fail.cpp
test/lightweight_test_gt_ge_test.cpp

Just LT and LE are insufficient for testing operator overloads.

Added BOOST_TEST_GT and BOOST_TEST_GE.

---

include/boost/core/lightweight_test.hpp

Last patch before deprecating old MSVC compilers

_set_abort_behavior not supported in old MSVC

---

doc/scoped_enum.qbk

I recently stumbled upon a case in which scoped enums have different behaviors in C++03 and C++11. I thought it would be a good idea to document this case.

Document an emulation limitation of scoped enum

---

doc/allocator_access.qbk
doc/core.qbk
include/boost/core/allocator_access.hpp
test/Jamfile.v2
test/allocator_allocate_hint_test.cpp
test/allocator_allocate_test.cpp
test/allocator_const_pointer_test.cpp
test/allocator_const_void_pointer_test.cpp
test/allocator_construct_test.cpp
test/allocator_deallocate_test.cpp
test/allocator_destroy_test.cpp
test/allocator_difference_type_test.cpp
test/allocator_is_always_equal_test.cpp
test/allocator_max_size_test.cpp
test/allocator_pocca_test.cpp
test/allocator_pocma_test.cpp
test/allocator_pocs_test.cpp
test/allocator_pointer_test.cpp
test/allocator_rebind_test.cpp
test/allocator_size_type_test.cpp
test/allocator_soccc_test.cpp
test/allocator_value_type_test.cpp
test/allocator_void_pointer_test.cpp

Instead of `allocator_traits` in Core, the same functionality provided by individual templates. This reflects recent C++ standard committee reflector discussion around how `allocator_traits` would be designed today instead.

Implement allocator utilities

---

include/boost/core/lightweight_test.hpp
test/Jamfile.v2
test/lightweight_test_with_test.cpp

Suggestion for #38.
Added BOOST_TEST_WITH macro. Moved operation name of built-in predicates to a traits class.

Added BOOST_TEST_WITH macro to verify test results with custom predicate

---

include/boost/core/uncaught_exceptions.hpp

Mac OS 10.4 and earlier lack Availability.h, causing compilation to fail. Rearrange the macro logic to include Availability.h only if we already think there may be support for uncaught exceptions.

Restore support for ancient Mac OS

---

.github/workflows/ci.yml

Earlier, I copied ci.yml from boostorg/core to boostorg/boost-ci where it can be used as a template when setting up new boost libraries.  Discovered a problem - if a new library doesn't yet exist in boost, the lib directory won't exist, and a copy will fail.   So, create the directory first.  It would be convenient to backport the change upstream, here.  Or even to any repo that might later be used as an example.

Small GHA fix, create destination dir

---

doc/allocator_access.qbk
doc/checked_delete.qbk
doc/demangle.qbk
doc/enable_if.qbk
doc/ignore_unused.qbk
doc/pointer_traits.qbk
doc/ref.qbk
doc/scoped_enum.qbk
doc/use_default.qbk

Use "Acknowledgments" everywhere for consistency.

Fix typos in docs

---

doc/core.qbk
doc/fclose_deleter.qbk
include/boost/core/fclose_deleter.hpp
test/Jamfile.v2
test/fclose_deleter_test.cpp
test/quick.cpp

`fclose_deleter` can be used as a deleter function object for `std::FILE` pointers returned by `std::fopen`.

Add fclose_deleter

---

include/boost/core/lightweight_test.hpp
include/boost/core/type_name.hpp

Use same method as https://github.com/boostorg/assert/commit/601ee4ba7ae9d9b532dab5f7e757f4187dce6300.

Fix for sprintf deprecation warning

---

include/boost/core/lightweight_test.hpp

This implements in-place formatting for small hex numbers instead of using `snprintf` with the associated portability scaffolding. This also removes the need for `#include <cstdio>`.
(I was going to use `boost/core/snprintf.hpp` initially, but figured it would be better to remove `snprintf` altogether.)

Remove the use of snprintf for trivial formatting in lightweight_test

---

include/boost/core/detail/sp_thread_pause.hpp

In building the Boost tests with the Intel compiler on Linux/amd64, I encountered this link error:
```
[ 10%] Linking CXX executable ../../../stage/bin/boost_core-yield_prim_pthread_cancel_test
icpc: warning #10182: disabling optimization; runtime debug checks enabled
CMakeFiles/boost_core-yield_prim_pthread_cancel_test.dir/yield_prim_pthread_cancel_test.cpp.o: In function `boost::core::sp_thread_pause()':
/tmp/boost/1.83.0/libs/core/include/boost/core/detail/sp_thread_pause.hpp:63: undefined reference to `__builtin_ia32_pause'
make[3]: *** [libs/core/test/CMakeFiles/boost_core-yield_prim_pthread_cancel_test.dir/build.make:97: stage/bin/boost_core-yield_prim_pthread_cancel_test] Error 1
make[2]: *** [CMakeFiles/Makefile2:12475: libs/core/test/CMakeFiles/boost_core-yield_prim_pthread_cancel …
```

Fix Intel compiler build

---

doc/changes.qbk
doc/core.qbk
doc/functor.qbk
include/boost/core/functor.hpp
test/Jamfile.v2
test/functor_test.cpp

This PR:
- Removes C++03 from CI
- Adds `boost/core/functor.hpp` with `functor` class template, as well as associated tests and docs.
`functor` is a C++17 utility class template that wraps a raw function into a function object class. The raw function is specified in a non-type template parameter, and hence its pointer is not stored internally as a data member (i.e. the `functor` class is empty). `functor::operator()` forwards any arguments to the wrapped raw function and returns its result.
The primary use case is converting raw deleter functions into function object classes for `std::unique_ptr`, `unique_resource` and similar. However, it may also be useful with `std::shared_ptr` and `std::bind` and similar utilities to improve efficiency (compared to using a pointer to function) and/or …

Add `functor`

---

include/boost/core/empty_value.hpp
test/Jamfile.v2
test/empty_value_compile_fail_casting.cpp
test/empty_value_test.cpp

See [unordered#257](https://github.com/boostorg/unordered/issues/257).
Is this a breaking change in Core? It doesn't break any tests, but is it conceptually wrong?

Fix `empty_value` MSVC bug

---

include/boost/core/empty_value.hpp

Using typedef `base` poses a high risk of name conflict, given that `empty_value` is inherited in user types.

Rename typedef `base` to `core_ev_base`

---

include/boost/core/detail/string_view.hpp

This is an issue for C++11 and up for e.g. Boost libs that want to ensure warning-free build.
Solution is simply to move the SFINAE expression to the template argument list to avoid the `<..>* = 0` default argument
Alternative: `enable_if<..., int>::type = 0`

Avoid `-Wzero-as-null-pointer-constant` warning in string_view ctor

---

include/boost/core/detail/sp_thread_sleep.hpp

Like Android, OpenHarmony doesn't support pthread_setcancelstate as well. The macro `__OHOS__` can be found in [llvm](https://github.com/llvm/llvm-project/blob/30ba8be22eb0e3f771624f6f47229129cf74e976/clang/lib/Basic/Targets/OSTargets.h#L989).
<details>
<code>
[4/5] Building CXX object libs/iostreams/CMakeFiles/boost_iostreams.dir/src/mapped_file.cpp.o
FAILED: libs/iostreams/CMakeFiles/boost_iostreams.dir/src/mapped_file.cpp.o 
/tmp/command-line-tools/sdk/default/openharmony/native/llvm/bin/clang++ --target=x86_64-linux-ohos --gcc-toolchain=/tmp/command-line-tools/sdk/default/openharmony/native/llvm --sysroot=/tmp/command-line-tools/sdk/default/openharmony/native/sysroot -DBOOST_IOSTREAMS_NO_LIB -DBOOST_IOSTREAMS_STATIC_LINK -DBOOST_RANDOM_NO_LIB -DBOOST_RANDOM_STATIC_LINK …

OpenHarmony doesn't support pthread_setcancelstate.

---

doc/span.qbk
include/boost/core/demangle.hpp
include/boost/core/scoped_enum.hpp
test/detail_iterator_test.cpp
test/swap/swap_no_ambiguity_in_boost.cpp
test/swap/swap_specialized_in_global.cpp

No functional changes intended.

Fix a few typos

---

.github/workflows/ci.yml

The Ubuntu 20.04 image on GitHub Actions will be unavailable by 2025-04-15. See <https://github.com/actions/runner-images/issues/11101> for more information on the deprecation and removal.
Therefore all build jobs that use the Ubuntu 20.04 runner image of GHA have to be either migrated to a newer runner image (if the compiler version is available on a newer image) or have to be moved to Docker containers using Ubuntu 20.04 (if the compiler version is not available on the newer runner images).

Move Ubuntu 20.04 builds to container or newer Ubuntu version

---

include/boost/core/bit.hpp
test/bit_ceil_test.cpp

This PR fixes a bug in `boost::core::bit_ceil()` where the function returned `0` for an input of `0`. According to the specification, it should return `1`.
- Corrected the implementation of `bit_ceil()` to return `1` when called with `0`.
- Added test coverage to validate the corrected behaviour.
Aligns the function with the expected and documented behaviour. This fix prevents potential logical errors in code relying on `bit_ceil(0)` returning `1`.

:bug: Fix bit_ceil() to return 1 for input 0 as per specification
